#!/bin/sh

Color_Off='\033[0m' 
BRed="\033[1;31m"         # Red
BGreen="\033[1;32m"       # Green
BYellow="\033[1;33m"      # Yellow
BBlue="\033[1;34m"        # Blue

MSG_FILE=$1
FILE_CONTENT="$(cat $MSG_FILE)"

export REGEX='(ITSSST-[0-9]+|ICT-[0-9]+)'
export ERROR_MSG="Commit message format must have Ticket Number ITSSST-XXXX or ICT-XXXXX"

if [[ $FILE_CONTENT =~ $REGEX ]]; then
 if [[ ${#FILE_CONTENT} < 30 ]]; then 
    printf "${BRed}Bad commit ${BBlue}\"$FILE_CONTENT\"\n"
    printf "${BYellow}You commit message lenght \"${#FILE_CONTENT}\" need to be greater than 30 charachters \n"
    exit 1
 fi
 printf "${BGreen}Good commit!${Color_Off}\n"
else
  printf "${BRed}Bad commit ${BBlue}\"$FILE_CONTENT\"\n"
  printf "${BYellow}$ERROR_MSG\n"
#  printf "commit-msg hook failed (add --no-verify to bypass)\n"
 
exit 1
fi

exit 0

