#!/bin/sh

Color_Off='\033[0m' 
BRed="\033[1;31m"         # Red
BGreen="\033[1;32m"       # Green
BYellow="\033[1;33m"      # Yellow
BBlue="\033[1;34m"        # Blue


FILE_CONTENT="$(git rev-parse --abbrev-ref HEAD)"
valid_chars="^[a-z0-9-]+$"
export REGEX='(ITSSST-[0-9]+|ICT-[0-9]+)'


if [[ ! $FILE_CONTENT =~ $REGEX ]]; then
    printf "${BRed}Bad Branch Name ${BBlue}\"$FILE_CONTENT\"\n"
    printf "${BYellow}You Branch Should Containes the Ticket Number ITSSST-XXXX or ICT-XXXX\n"
    exit 1
fi

if [[ ! $FILE_CONTENT =~ "feature" ]]; then
    printf "${BRed}Bad Branch Name ${BBlue}\"$FILE_CONTENT\"\n"
    printf "${BYellow}You Organization block pushing commit to Branch\"$FILE_CONTENT\" only feature Branches are valid to push \n"
    exit 1
fi



exit 0